[package]
name = "leafwing_input_playback"
description = "Input recording and mocking functionality for the Bevy game engine."
version = "0.3.0"
authors = ["Leafwing Studios"]
homepage = "https://leafwing-studios.com/"
repository = "https://github.com/leafwing-studios/leafwing_input_playback"
license = "MIT OR Apache-2.0"
edition = "2021"
categories = ["games", "game-development"]
keywords = ["bevy", "input"]
exclude = ["assets/**/*", "tools/**/*", ".github/**/*"]

[profile.dev]
opt-level = 3

[workspace]
members = ["./", "tools/ci"]

[features]
default = []

[dependencies]
bevy_app = {version = "0.8", default-features = false}
bevy_ecs = {version = "0.8", default-features = false}
bevy_input = {version = "0.8", default-features = false, features = ["serialize"]}
bevy_time = {version = "0.8", default-features = false}
bevy_utils = {version = "0.8", default-features = false}
bevy_window = {version = "0.8", default-features = false}


serde = {version = "1.0", features = ["derive"]}

[dev-dependencies]
bevy = {version = "0.8", default-features = true}

[lib]
name = "leafwing_input_playback"
path = "src/lib.rs"

[tests]
# Some tests must be run on the main thread, as they require access to main-thread-only resources
# This is ultimately because of https://github.com/bevyengine/bevy/issues/6106
# Solution borrowed from
# https://stackoverflow.com/questions/43458194/is-there-any-way-to-tell-cargo-to-run-its-tests-on-the-main-thread
name = "gltests"
path = "gltests/main.rs"
harness = false
