[package]
name = "leafwing_input_playback"
description = "Input recording and mocking functionality for the Bevy game engine."
version = "0.3.0"
authors = ["Leafwing Studios"]
homepage = "https://leafwing-studios.com/"
repository = "https://github.com/leafwing-studios/leafwing_input_playback"
license = "MIT OR Apache-2.0"
edition = "2021"
categories = ["games", "game-development"]
keywords = ["bevy", "input"]
exclude = ["assets/**/*", "tools/**/*", ".github/**/*"]

[profile.dev]
opt-level = 3

[workspace]
members = ["./", "tools/ci"]

[features]
default = []

[dependencies]
bevy_app = {version = "0.8", default-features = false}
bevy_ecs = {version = "0.8", default-features = false}
bevy_input = {version = "0.8", default-features = false}
bevy_math = {version = "0.8", default-features = false}
bevy_utils = {version = "0.8", default-features = false}
bevy_window = {version = "0.8", default-features = false}
bevy_winit = {version = "0.8", default-features = false}

# This must exactly match the dependency in bevy_window at
# winit = https://github.com/bevyengine/bevy/blob/latest/crates/bevy_winit/Cargo.toml
winit = { version = "0.26.0", default-features = false }
serde = {version = "1.0", features = ["derive"]}
# Used by vendored reimplementation of winit_runner :(
approx = { version = "0.5.0", default-features = false }

[dev-dependencies]
bevy = {version = "0.8", default-features = false}

[lib]
name = "leafwing_input_playback"
path = "src/lib.rs"
